/** User-facing vocabulary — treasury office (admin). */
export const adminCopy = {
  officeTitle: "Treasury Office",
  treasury: "Treasury",
  chamber: "Chamber",
  tokenStats: "Token Stats",
  treasuryPageTitle: "Treasury",
  treasuryPageDescription: (wrappedName: string, wrappedSymbol: string) =>
    `Issue ${wrappedName} from reserve collateral held by the treasury signer, or redeem ${wrappedSymbol} for underlying. The backend signs and submits transactions. Amounts are in smallest on-chain units.`,
  treasurySigner: "Treasury signer",
  treasuryOperations: "Treasury operations",
  reserveGovernance: "Reserve governance",
  tokenStatsSubtitle: "Token address & holders",
  tokenStatsPageTitle: "Token Stats",
  tokenStatsPageDescription: (wrappedName: string, wrappedSymbol: string) =>
    `${wrappedName} (${wrappedSymbol}) mint metadata and largest token-account holders from the treasury API.`,
  tokenContract: "Token Contract",
  decimals: "Decimals",
  holdersBreakdown: "Token Holders Breakdown",
  holdersCaption:
    "Top five token accounts by balance; remaining supply rolled into Others. Addresses are SPL token accounts.",
  holdersOthers: "Others",
  holdersEmpty: "No holder balances reported yet.",
  refreshHolders: "Refresh holders",
  accounts: "Accounts",
  accountsCaption:
    "Per-pool reserves, liability, and redeemable capacity. Figures in token base units unless noted.",
  issueViaTreasury: "Issue via treasury",
  redeemViaTreasury: "Redeem via treasury",
  submitting: "Submitting…",
  refreshLedger: "Refresh ledger",
  reserveGovernanceSubtitle: "Reserve governance",
  collateralPolicy: "Reserve governance",
  tabMint: "Mint Florin",
  tabRedeem: "Redeem Florin",
  reserveCollateral: "Reserve collateral",
  collateralAmount: "Collateral amount (base units)",
  redeemAmount: (symbol: string) => `${symbol} amount to redeem`,
  pausedVaultAlert:
    "Vault is paused. Mint, redeem, Kamino deposit, and harvest are blocked. Recall, sweep, and treasury withdrawal still work.",
  klendNav: "Yield",
  klendSubtitle: "Kamino liquidity",
  klendPageTitle: "Yield",
  klendPageDescription:
    "Deploy home-vault collateral to Kamino, recall liquidity for redemptions, harvest yield, and sweep surplus. Amounts are in smallest on-chain units. Harvest is capped on-chain.",
  klendNoAssets: "No registered collateral assets.",
  klendNotEnabled: "Kamino is not enabled for this asset. Vault-only ops (sweep, treasury withdraw) still apply.",
  klendDeploy: "Deploy",
  klendDeployAll: "Deploy all",
  klendRecall: "Recall",
  klendRecallAll: "Recall all",
  klendHarvest: "Harvest",
  klendHarvestHint: "kToken amount; on-chain harvest_yield enforces the surplus cap.",
  klendSweep: "Sweep surplus",
  klendWithdrawTreasury: "Withdraw treasury",
  klendDeployAmount: "Deploy amount (base units)",
  klendRecallAmount: "Recall amount (kTokens)",
  klendHarvestAmount: "Harvest amount (kTokens)",
  klendSweepAmount: "Sweep amount (base units)",
  klendTreasuryAmount: "Treasury amount",
  klendDestination: "Destination wallet",
  vaultControls: "Vault controls",
  vaultControlsSubtitle:
    "Pause, public wrap/unwrap, allowlist, admin transfer, and mint-authority handoff. Server-signed except accept, which uses a destination keypair file in this browser.",
  wrapPermanentlyDisabled:
    "Mint authority has been transferred. Wrap is permanently disabled on this vault; unwrap still follows per-pool policy.",
  pauseLabel: "Paused",
  wrapPublicLabel: "Wrap public",
  unwrapPublicLabel: "Unwrap public",
  allowlistTitle: "Allowlist",
  allowlistMissing: "Allowlist PDA is not initialized. Required when wrap or unwrap is not public.",
  initAllowlist: "Initialize allowlist",
  addAllowlistMember: "Add members",
  allowlistPubkey: "Wallet pubkeys (one per line)",
  allowlistEmpty: "No members.",
  allowlistCapHint: "On-chain max is 64 wallets. This is a protocol limit, not a UI limit.",
  allowlistCount: (n: number, max: number) => `${n} / ${max}`,
  privateFlagConfirm:
    "Allowlist is empty or missing. Only the admin wallet will be able to wrap or unwrap. Continue?",
  adminTransferTitle: "Admin transfer",
  newAdminPubkey: "New admin pubkey",
  proposeAdmin: "Propose",
  cancelAdminTransfer: "Cancel proposal",
  pendingAdmin: "Pending admin",
  acceptAdmin: "Accept as pending admin",
  keypairFile: "Destination keypair JSON",
  mintAuthorityTitle: "Mint authority",
  newMintAuthorityPubkey: "New mint authority pubkey",
  proposeMintAuthority: "Propose",
  cancelMintAuthority: "Cancel proposal",
  pendingMintAuthority: "Pending mint authority",
  acceptMintAuthority: "Accept mint authority",
  disableWrapConfirmLabel: 'Type DISABLE WRAP to confirm',
  disableWrapPhrase: "DISABLE WRAP",
  mintAuthorityAcceptWarning:
    "Accepting mint authority permanently disables wrap on this vault and moves SPL mint authority to the destination. Unwrap remains available for existing liability.",
  enableKlend: "Enable Kamino",
  enableKlendHint: "One-shot. Lending market, reserve, liquidity supply, and collateral mint must match the Kamino market for this asset.",
  lendingMarket: "Lending market",
  klendReserve: "Reserve",
  reserveLiquiditySupply: "Reserve liquidity supply",
  collateralMint: "Collateral mint (kToken)",
} as const;
