/**
 * Generate a deterministic test wallet (first run only — persists to
 * fixtures/user/wallet.json) and build a USDC ATA fixture at that wallet's ATA
 * pubkey with a large balance. The test validator loads this via
 * [[test.validator.account]] so the e2e test has a funded wallet without having
 * to touch Circle's mint authority.
 *
 * Run:
 *   yarn ts-node scripts/make_user_fixture.ts
 *
 * Env overrides:
 *   OUT_DIR  output directory (default: fixtures/user)
 *   MINT     mint to fund (default: USDC)
 *   AMOUNT   token amount in smallest units (default: 1_000_000_000_000 = 1M USDC)
 */

import {
  Keypair,
  PublicKey,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  ACCOUNT_SIZE,
  AccountLayout,
  AccountState,
  TOKEN_PROGRAM_ID,
  getAssociatedTokenAddressSync,
} from "@solana/spl-token";
import * as fs from "node:fs";
import * as path from "node:path";

const OUT_DIR = process.env.OUT_DIR ?? "fixtures/user";
const MINT = new PublicKey(
  process.env.MINT ?? "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
);
const AMOUNT = BigInt(process.env.AMOUNT ?? "1000000000000"); // 1M USDC
const ACCOUNT_RENT_LAMPORTS = 2_039_280; // rent-exempt reserve for 165-byte account
const WALLET_SOL = 100 * LAMPORTS_PER_SOL;

const WALLET_PATH = path.join(OUT_DIR, "wallet.json");
const WALLET_ACCOUNT_PATH = path.join(OUT_DIR, "wallet_account.json");
const USDC_ATA_PATH = path.join(OUT_DIR, "usdc_ata.json");
const MANIFEST_PATH = path.join(OUT_DIR, "manifest.toml");

function loadOrCreateWallet(): Keypair {
  if (fs.existsSync(WALLET_PATH)) {
    const secret = JSON.parse(fs.readFileSync(WALLET_PATH, "utf8"));
    return Keypair.fromSecretKey(Uint8Array.from(secret));
  }
  const kp = Keypair.generate();
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(WALLET_PATH, JSON.stringify(Array.from(kp.secretKey)));
  console.error(`Generated new test wallet: ${kp.publicKey.toBase58()}`);
  return kp;
}

function encodeTokenAccount(
  mint: PublicKey,
  owner: PublicKey,
  amount: bigint,
): Buffer {
  const data = Buffer.alloc(ACCOUNT_SIZE);
  AccountLayout.encode(
    {
      mint,
      owner,
      amount,
      delegateOption: 0,
      delegate: PublicKey.default,
      state: AccountState.Initialized,
      isNativeOption: 0,
      isNative: 0n,
      delegatedAmount: 0n,
      closeAuthorityOption: 0,
      closeAuthority: PublicKey.default,
    },
    data,
  );
  return data;
}

function writeAccountFixture(
  filename: string,
  pubkey: PublicKey,
  owner: PublicKey,
  lamports: number,
  data: Buffer,
): void {
  const body = `{
  "pubkey": "${pubkey.toBase58()}",
  "account": {
    "lamports": ${lamports},
    "data": [
      "${data.toString("base64")}",
      "base64"
    ],
    "owner": "${owner.toBase58()}",
    "executable": false,
    "rentEpoch": 18446744073709551615,
    "space": ${data.length}
  }
}
`;
  fs.writeFileSync(filename, body);
}

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const wallet = loadOrCreateWallet();
  const ata = getAssociatedTokenAddressSync(MINT, wallet.publicKey);

  // Fund the wallet's native SOL balance. System-program-owned account with
  // empty data — solana-test-validator accepts this as a funded wallet.
  writeAccountFixture(
    WALLET_ACCOUNT_PATH,
    wallet.publicKey,
    new PublicKey("11111111111111111111111111111111"),
    WALLET_SOL,
    Buffer.alloc(0),
  );

  // USDC ATA for the wallet.
  const usdcData = encodeTokenAccount(MINT, wallet.publicKey, AMOUNT);
  writeAccountFixture(
    USDC_ATA_PATH,
    ata,
    TOKEN_PROGRAM_ID,
    ACCOUNT_RENT_LAMPORTS,
    usdcData,
  );

  const manifest = [
    `# Generated by scripts/make_user_fixture.ts`,
    `# Wallet: ${wallet.publicKey.toBase58()}`,
    `# Mint:   ${MINT.toBase58()}`,
    `# ATA:    ${ata.toBase58()}`,
    `# Amount: ${AMOUNT}`,
    ``,
    `# Test wallet SOL balance`,
    `[[test.validator.account]]`,
    `address = "${wallet.publicKey.toBase58()}"`,
    `filename = "${WALLET_ACCOUNT_PATH}"`,
    ``,
    `# Test wallet USDC ATA`,
    `[[test.validator.account]]`,
    `address = "${ata.toBase58()}"`,
    `filename = "${USDC_ATA_PATH}"`,
    ``,
  ].join("\n");
  fs.writeFileSync(MANIFEST_PATH, manifest);

  console.error(`Wallet:     ${wallet.publicKey.toBase58()}`);
  console.error(`USDC ATA:   ${ata.toBase58()}`);
  console.error(`Fixtures:   ${WALLET_ACCOUNT_PATH}, ${USDC_ATA_PATH}`);
  console.error(`Manifest:   ${MANIFEST_PATH}`);
}

main();
