/**
 * Print [[test.validator.clone]] blocks for Anchor.toml so a local validator can be
 * bootstrapped with Kamino KLend state cloned from mainnet. Targets the USDC reserve
 * on the given market.
 *
 * Run:
 *   yarn ts-node scripts/print_klend_clones.ts
 *
 * Env overrides:
 *   RPC_URL     mainnet RPC endpoint (default: public mainnet-beta)
 *   MARKET      lending market pubkey (default: Kamino Main Market)
 *   MINT        reserve liquidity mint to target (default: USDC)
 */

import { Address, address, createSolanaRpc } from "@solana/kit";
import { KaminoMarket } from "@kamino-finance/klend-sdk";

const RPC_URL = process.env.RPC_URL ?? "https://api.mainnet-beta.solana.com";
// Kamino Main Market on mainnet (houses USDC, SOL, USDT, etc.)
const MARKET: Address = address(
  process.env.MARKET ?? "7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF",
);
// USDC mainnet
const MINT: Address = address(
  process.env.MINT ?? "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
);
const DEFAULT_ADDRESS = "11111111111111111111111111111111" as Address;
// Mainnet slot time, in ms. Used by the SDK to age-weight slot-dependent calcs;
// exact value doesn't affect the fields we read.
const SLOT_DURATION_MS = 450;

function tomlBlock(label: string, addr: Address): string {
  return `# ${label}\n[[test.validator.clone]]\naddress = "${addr}"\n`;
}

async function main() {
  const rpc = createSolanaRpc(RPC_URL);

  console.error(`Loading KLend market ${MARKET} …`);
  const market = await KaminoMarket.load(rpc, MARKET, SLOT_DURATION_MS);
  if (!market) {
    throw new Error(`failed to load market ${MARKET}`);
  }

  const reserve = market.getReserveByMint(MINT);
  if (!reserve) {
    throw new Error(`no reserve for mint ${MINT} on market ${MARKET}`);
  }

  const state = reserve.state;
  const liqSupply: Address = state.liquidity.supplyVault;
  const collateralMint: Address = state.collateral.mintPubkey;
  const feeVault: Address = state.liquidity.feeVault;

  // Oracle fan-out. Kamino reserves can be configured with Pyth, Switchboard price,
  // Switchboard TWAP, and/or a Scope prices account. Clone whichever are set.
  const pyth: Address = state.config.tokenInfo.pythConfiguration.price;
  const sbPrice: Address =
    state.config.tokenInfo.switchboardConfiguration.priceAggregator;
  const sbTwap: Address =
    state.config.tokenInfo.switchboardConfiguration.twapAggregator;
  const scopePrices: Address =
    state.config.tokenInfo.scopeConfiguration.priceFeed;

  const klendProgramId: Address = address(
    "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",
  );

  const lines: string[] = [];
  lines.push(`# --- KLend clones for USDC on Kamino Main Market ---`);
  lines.push(`# Generated by scripts/print_klend_clones.ts. Regenerate if reserve config changes.`);
  lines.push(``);
  lines.push(`[test.validator]`);
  lines.push(`url = "${RPC_URL}"`);
  lines.push(``);
  lines.push(
    tomlBlock(
      "KLend program (already loaded via [[test.genesis]])",
      klendProgramId,
    ),
  );
  lines.push(tomlBlock("Lending market", MARKET));
  lines.push(tomlBlock("USDC reserve", reserve.address));
  lines.push(
    tomlBlock("Reserve liquidity supply (reserve.liquidity.supplyVault)", liqSupply),
  );
  lines.push(tomlBlock("Reserve collateral mint (kUSDC)", collateralMint));
  lines.push(tomlBlock("Reserve fee vault", feeVault));
  lines.push(tomlBlock("Reserve liquidity mint (USDC)", MINT));

  if (pyth !== DEFAULT_ADDRESS) {
    lines.push(tomlBlock("Pyth USDC price account", pyth));
  }
  if (sbPrice !== DEFAULT_ADDRESS) {
    lines.push(tomlBlock("Switchboard price aggregator", sbPrice));
  }
  if (sbTwap !== DEFAULT_ADDRESS) {
    lines.push(tomlBlock("Switchboard TWAP aggregator", sbTwap));
  }
  if (scopePrices !== DEFAULT_ADDRESS) {
    lines.push(tomlBlock("Scope prices account", scopePrices));
  }

  lines.push(`# Lending market authority PDA is derived on-chain from the market pubkey,`);
  lines.push(`# so no clone is needed for it.`);

  process.stdout.write(lines.join("\n") + "\n");

  console.error(`\nOK. Reserve = ${reserve.address}`);
  console.error(
    `Oracles: pyth=${pyth} sbPrice=${sbPrice} sbTwap=${sbTwap} scope=${scopePrices}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
