/**
 * Render backend/.env and the frontend .env.local files from
 * deployments/<network>.json.
 *
 * Merge rule for backend/.env: managed keys are rewritten, unrelated keys
 * (ADMIN_KEYPAIR_PATH, SECRET_NAME, ...) are preserved.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { Deployment, readDeployment, relative } from "../deployments";
import { Network, NETWORKS, REPO_ROOT } from "../network";

const BACKEND_ENV = path.join(REPO_ROOT, "backend/.env");
const FRONTEND_ENV_LOCAL = path.join(REPO_ROOT, "frontend/.env.local");
const ADMIN_ENV_LOCAL = path.join(REPO_ROOT, "admin-frontend/.env.local");

const MANAGED_KEYS = [
  "APP_ENV",
  "SOLANA_RPC_URL",
  "SOLANA_NETWORK",
  "PROGRAM_ID",
  "VAULT_AUTHORITY",
  "DEFAULT_ASSET_MINT",
  "CLIENT_SOLANA_RPC_URL",
  "CLIENT_SOLANA_WS_URL",
] as const;

/**
 * Keys earlier generations wrote that nothing reads: retired aliases of
 * CLIENT_SOLANA_*, and addresses the backend derives from PROGRAM_ID +
 * VAULT_AUTHORITY. Dropped on every regeneration.
 */
const RETIRED_KEYS = [
  "PUBLIC_SOLANA_RPC_URL",
  "PUBLIC_SOLANA_WS_URL",
  "WRAPPED_MINT",
  "VAULT_CONFIG",
];

/** backend/src/config/public_client_config.rs AppEnvironment. */
const APP_ENV: Record<Network, string> = {
  localnet: "local",
  devnet: "development",
  mainnet: "production",
};

function parseEnvFile(content: string): Map<string, string> {
  const env = new Map<string, string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    env.set(trimmed.slice(0, eq).trim(), trimmed.slice(eq + 1).trim());
  }
  return env;
}

function formatEnvFile(env: Map<string, string>, header: string): string {
  const managed = new Set<string>(MANAGED_KEYS);
  const lines = [header, ""];
  for (const key of MANAGED_KEYS) {
    if (env.has(key)) lines.push(`${key}=${env.get(key)}`);
  }
  const extras = [...env]
    .filter(([key]) => !managed.has(key))
    .map(([key, value]) => `${key}=${value}`)
    .sort();
  if (extras.length > 0) {
    lines.push("", "# Preserved local overrides", ...extras);
  }
  lines.push("");
  return lines.join("\n");
}

function writeFile(file: string, body: string, dryRun: boolean): void {
  if (!dryRun) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
  }
  console.log(`  ${relative(file)}`);
}

export function syncEnv(dep: Deployment, dryRun = false): void {
  const env = fs.existsSync(BACKEND_ENV)
    ? parseEnvFile(fs.readFileSync(BACKEND_ENV, "utf8"))
    : new Map<string, string>();
  for (const key of RETIRED_KEYS) env.delete(key);
  // backend/src/config/env.rs resolves `{KEY}_{NETWORK}` before the bare key, so a
  // leftover scoped override would silently win over the value written just below.
  for (const key of MANAGED_KEYS) {
    for (const network of NETWORKS) env.delete(`${key}_${network.toUpperCase()}`);
  }

  const updates: Record<string, string> = {
    APP_ENV: APP_ENV[dep.cluster],
    SOLANA_RPC_URL: dep.rpcUrl,
    SOLANA_NETWORK: dep.cluster,
    PROGRAM_ID: dep.programId,
    VAULT_AUTHORITY: dep.authority,
    DEFAULT_ASSET_MINT: dep.defaultAssetMint,
    CLIENT_SOLANA_RPC_URL: dep.rpcUrl,
    CLIENT_SOLANA_WS_URL: dep.wsUrl,
  };
  for (const [key, value] of Object.entries(updates)) env.set(key, value);

  // Operator-owned keys: seed a working default, never overwrite.
  // /v1/admin/* is unauthenticated, so a hosted cluster stays on loopback.
  if (!env.get("BIND_HOST")) {
    env.set("BIND_HOST", dep.cluster === "localnet" ? "0.0.0.0" : "127.0.0.1");
  }
  if (!env.get("BIND_PORT")) env.set("BIND_PORT", "8080");
  if (dep.cluster === "localnet" && !env.get("ADMIN_KEYPAIR_PATH")) {
    env.set("ADMIN_KEYPAIR_PATH", ".secrets/admwu2g9WV2kdwTzjasLXTy7tWq3W15BrP4PE7UZJ5x.json");
  }
  // DEPLOYMENT_ID is required by the backend whenever APP_ENV is not local.
  if (dep.cluster !== "localnet" && !env.get("DEPLOYMENT_ID")) {
    env.set("DEPLOYMENT_ID", `${dep.cluster}-1`);
  }

  console.log(dryRun ? "─── Env files (dry-run) ───" : "─── Env files synced ───");
  writeFile(
    BACKEND_ENV,
    formatEnvFile(
      env,
      `# Generated by \`pnpm cli sync-env --network ${dep.cluster}\` from ${dep.cluster}.json.\n# Unrelated keys below are preserved across regenerations.`,
    ),
    dryRun,
  );

  const frontendBody =
    "# Sole public deployment env — all other config from GET /v1/client-config\n" +
    `NEXT_PUBLIC_BACKEND_URL=${dep.backendUrl}\n`;
  writeFile(FRONTEND_ENV_LOCAL, frontendBody, dryRun);
  writeFile(ADMIN_ENV_LOCAL, frontendBody, dryRun);
  console.log("────────────────────────");
}

export function syncEnvCommand(network: Network, dryRun: boolean): void {
  syncEnv(readDeployment(network), dryRun);
}
