[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
wrap_stablecoin = "BZQaR9BcpRBnGedU6BPAWwocHwvdCdjcJYD1doCVXhcS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = ".secrets/admwu2g9WV2kdwTzjasLXTy7tWq3W15BrP4PE7UZJ5x.json"

[scripts]
local = "bash scripts/run_local.sh"
local-stop = "bash scripts/local_stop.sh"
stop-local = "bash scripts/local_stop.sh"
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/cross_asset.ts tests/e2e.ts"

[test]
startup_wait = 50000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
program = "so/klend.so"
upgradeable = true

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
warp_slot = 413424802

[[test.validator.account]]
address = "7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF"
filename = "fixtures/klend/lending_market.json"

[[test.validator.account]]
address = "D6q6wuQSrifJKZYpR1M8R4YawnLDtDsMmWM1NbBmgJ59"
filename = "fixtures/klend/reserve.json"

[[test.validator.account]]
address = "Bgq7trRgVMeq33yt235zM2onQ4bRDBsY5EWiTetF4qw6"
filename = "fixtures/klend/reserve_liquidity_supply.json"

[[test.validator.account]]
address = "B8V6WVjPxW1UGwVDfxH2d2r8SyT4cqn7dQRK6XneVa7D"
filename = "fixtures/klend/reserve_collateral_mint.json"

[[test.validator.account]]
address = "BbDUrk1bVtSixgQsPLBJFZEF7mwGstnD5joA1WzYvYFX"
filename = "fixtures/klend/reserve_fee_vault.json"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "fixtures/klend/liquidity_mint_usdc.json"

[[test.validator.account]]
address = "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH"
filename = "fixtures/klend/scope_prices.json"

[[test.validator.account]]
address = "admwu2g9WV2kdwTzjasLXTy7tWq3W15BrP4PE7UZJ5x"
filename = "fixtures/user/wallet_account.json"

[[test.validator.account]]
address = "5wV2s8cBkF5K2aLiWRSvEj8JFeq4GtvnvjskKebrQRDK"
filename = "fixtures/user/usdc_ata.json"
