/** User-facing vocabulary — public merchant app. */
export const publicCopy = {
  pageTitle: "Issue & redeem",
  pageDescription:
    "Issue Florin against registered reserve collateral or redeem Florin for underlying.",
  tabIssue: "Issue Florin",
  tabRedeem: "Redeem Florin",
  tabsAriaLabel: "Issue or redeem Florin",
  holdings: "Holdings",
  holdingsColumn: "Holdings",
  connectAccount: "Connect account",
  merchantAccount: "Merchant account",
  connectedAccount: "Connected account",
  changeAccount: "Change account",
  copyAddress: "Copy address",
  disconnect: "Disconnect",
  reserveCollateral: "Reserve collateral",
  refreshLedger: "Refresh ledger",
  collateralAmount: "Collateral amount",
  humanAmountHint: "Enter a human amount (e.g. 1.0), not base units.",
  redeemAmount: (symbol: string) => `${symbol} amount to redeem`,
  max: "Max",
  walletBalance: (amount: string, symbol: string) => `Wallet: ${amount} ${symbol}`,
  redeemableBalance: (amount: string, symbol: string) => `Redeemable: ${amount} ${symbol}`,
  connectForBalance: "Connect a wallet to use Max.",
  loadingBalance: "Loading wallet balance…",
  balanceUnavailable: "Couldn't load wallet balance (RPC busy). Try Refresh ledger.",
  viewOnExplorer: "View on Solscan",
  signAndSend: "Sign & send",
  simulate: "Simulate",
  signing: "Signing…",
  headerTagline: "Issue & redeem",
  pausedAlert: "Vault is paused. Issue and redeem are blocked until an operator clears pause.",
  mintAuthorityTransferredAlert:
    "Token mint authority has been transferred. Issuing is permanently disabled; redeem still follows pool policy.",
  issueDisabledAlert: "Issuing is disabled for this asset pool.",
  redeemDisabledAlert: "Redemption is disabled for this asset pool.",
  issueHaircut: (pct: string) => ` (${pct} issue haircut)`,
  redeemHaircut: (pct: string) => ` (${pct} redemption haircut)`,
  issueCapRemaining: (amount: string, symbol: string) =>
    `Issue cap remaining: ${amount} ${symbol}`,
  wrapPrivateAlert: "Issue is allowlist-only. Your connected wallet is not on the list.",
  unwrapPrivateAlert: "Redeem is allowlist-only. Your connected wallet is not on the list.",
  wrapPrivateListed: "Issue is allowlist-only. Your wallet is listed.",
  unwrapPrivateListed: "Redeem is allowlist-only. Your wallet is listed.",
  wrapPrivateDisconnected: "Issue is allowlist-only. Connect a listed wallet to issue.",
  unwrapPrivateDisconnected: "Redeem is allowlist-only. Connect a listed wallet to redeem.",
} as const;
